name: firebase_dynamic_links
description: Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 0.5.0+9
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  url_launcher: ^4.2.0
  firebase_core: ^0.4.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasedynamiclinks
        pluginClass: FirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
