name: firebase_remote_config
description: Flutter plugin for Firebase Remote Config. Update your application look and feel and behaviour without
  re-releasing.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config
version: 0.3.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebaseremoteconfig
        pluginClass: FirebaseRemoteConfigPlugin
      ios:
         pluginClass: FirebaseRemoteConfigPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
