name: cloud_functions
description: Flutter plugin for Cloud Functions.
version: 0.4.1+6
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.cloudfunctions
        pluginClass: CloudFunctionsPlugin
      ios:
        pluginClass: CloudFunctionsPlugin

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=1.10.0 <2.0.0'
