name: firebase_in_app_messaging
description: Flutter plugin for Firebase In-App Messaging.
version: 0.1.1+1
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.2.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.example.firebase_in_app_messaging
        pluginClass: FirebaseInAppMessagingPlugin
      ios:
        pluginClass: FirebaseInAppMessagingPlugin
