name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 0.1.2+4
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.9.3

dev_dependencies:
  e2e: ^0.2.1
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics.firebasecrashlytics
        pluginClass: FirebaseCrashlyticsPlugin
      ios:
        pluginClass: FirebaseCrashlyticsPlugin

