name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database
version: 3.1.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
